common: &common
  adapter: mysql2
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  charset: utf8
  collation: utf8_bin
  pool: 5
  timeout: 5000

development:
  <<: *common
  database: attendance_development

test:
  <<: *common
  database: attendance_test

production:
  <<: *common
  database: attendance
