# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)
Classification.create(:name => "reg_ed", :display_name => "Regular Education", :rate => 28.00)
Classification.create(:name => "spec_ed", :display_name => "Special Education", :rate => 35.00)
Classification.create(:name => "basic_bundled", :display_name => "Basic Bundled", :rate => 109.50)
Classification.create(:name => "basic_bundled_spec_ed", :display_name => "Basic Bundled Special Education", :rate => 116.50)
Classification.create(:name => "premium_bundled", :display_name => "Premium Bundled", :rate => 119.50)
Classification.create(:name => "premium_bundled_spec_ed", :display_name => "Premium Bundled Special Education", :rate => 126.50)

School.create(:name => "Beavercreek")
School.create(:name => "Bellbrook")
School.create(:name => "Brookville")
School.create(:name => "Chappie James")
School.create(:name => "Dayton Leadership Academy")
School.create(:name => "Dayton Public")
School.create(:name => "Dayton Technology")
School.create(:name => "Fairborn")
School.create(:name => "Huber Heights")
School.create(:name => "ISUS")
School.create(:name => "Jefferson Montessori")
School.create(:name => "Jefferson Twp.")
School.create(:name => "Kettering")
School.create(:name => "Mad River")
School.create(:name => "Mound Street")
School.create(:name => "NCCS")
School.create(:name => "New Lebanon")
School.create(:name => "North Dayton")
School.create(:name => "Northmont")
School.create(:name => "Northridge")
School.create(:name => "Richard Allen")
School.create(:name => "The Dayton Academy")
School.create(:name => "Trotwood-Madison")
School.create(:name => "Vandalia Butler")
School.create(:name => "West Carrollton")
School.create(:name => "World of Wonder")
School.create(:name => "Valley View")
School.create(:name => "Centerville")
School.create(:name => "Miamisburg")
School.create(:name => "Beavercreek")
School.create(:name => "Springboro")
School.create(:name => "Life Skills in Dayton")
School.create(:name => "Horizon Science Academy")
School.create(:name => "TechCon")
